### ISSUE TITLE
Bug in do_ftemp_kphio

### ISSUE THREAD

**Issue by davidorme** [computationales/rpmodel#17] opened 2022-02-15 14:21 UTC
The same issue as in #16 also affect the mechanics of `do_ftemp_kphio`:

https://github.com/computationales/rpmodel/blob/master/R/rpmodel.R#L287

```r
  kphio <- ifelse(
    do_ftemp_kphio,
    ftemp_kphio( tc, c4 ) * kphio,
    kphio
  )
```

The argument `do_ftemp_kphio` is a logical value, so this structure _guarantees_ that `kphio` will be truncated when `do_ftemp_kphio` is `TRUE`:

```r
> kphio <- ifelse(TRUE, c('lots', 'of', 'numbers'), c('some', 'other','numbers'))                                                                             
> kphio                                                                                                                                               
[1] "lots"
```

I am working on fixes for these bugs - I'll submit some pull requests!

**Comment by stineb** [comment] 2022-02-23 14:12
rpmodel is not designed to treat vectors of forcings other than what is typically considered to be temporally varying for site-level runs, see vignette 'Usage', section 'P-model for time series'.

**Comment by stineb** [comment] 2022-02-23 14:36
Hi @davidorme 

Thanks for checking. I don't see how `tc` is truncated. Running with time series forcing and with `do_ftemp_kphio = TRUE` and with  `do_ftemp_kphio = c(TRUE, FALSE)` returns identical output. Which is intended (only first element will be used, as new warning says).

**Comment by stineb** [comment] 2022-02-23 14:48
Can you show a reproducible example with an rpmodel call to demonstrate the problem? I don't see the issue, sorry.

**Comment by davidorme** [comment] 2022-02-23 15:04
Aha - tricky now, because the issue has been resolved when you accepted my pull request #18 ! However, if I install a version from before the pull (6c93cc4b39842d27d391936235ac55872a4faba5), and then run two models, identical except for the order of the `tc`, you'll see you don't get a simple inversion of the results. 

The problem is that `kphio` gets truncated to a scalar (all calculations use `tc[1]`) but the full vector of `tc` gets used in most other calculations.

```r
 rpmodel( 
   tc             = c(20, 22),
   vpd            = c(1000, 1000),
   co2            = c(400, 400),
   fapar          = c(1, 1),
   ppfd           = c(30, 30),
   elv            = 0,
   kphio          = 0.049977,
   beta           = 146,
   c4             = FALSE,
   method_optci   = "prentice14",
   method_jmaxlim = "none",
   do_ftemp_kphio = TRUE,
   do_soilmstress = FALSE,
   verbose        = FALSE
  )$gpp
[1] 8.414510 8.216256

> rpmodel( 
   tc             = c(22, 20),
   vpd            = c(1000, 1000),
   co2            = c(400, 400),
   fapar          = c(1, 1),
   ppfd           = c(30, 30),
   elv            = 0,
   kphio          = 0.049977,
   beta           = 146,
   c4             = FALSE,
   method_optci   = "prentice14",
   method_jmaxlim = "none",
   do_ftemp_kphio = TRUE,
   do_soilmstress = FALSE,
   verbose        = FALSE
   )$gpp
[1] 8.409638 8.612559
```

**Comment by rmcnellis** [comment] 2022-02-23 15:29
I think the issues with `ifelse` is easiest to see if you pull the code out of the model, since the model doesn't output `kphio`

```
do_ftemp_kphio <- TRUE
tc <- c(20, 25, 30)
c4 <- FALSE
kphio_in <- 0.081785

ifelse(do_ftemp_kphio, 
        kphio <- ftemp_kphio( tc, c4 ) * kphio_in,
        kphio)
[1] 0.05365096

if (do_ftemp_kphio){
     kphio <- ftemp_kphio( tc, c4 ) * kphio_in
 }
kphio
[1] 0.05365096 0.05639076 0.05774021
```
But as @davidorme said, the issue is resolved with the last commit, since `ifelse` is no longer being used.

**Comment by davidorme** [comment] 2022-02-24 17:07
@stineb - I think this is now closed, with the recent pull request.

**Closed** 2023-02-13 12:36 UTC
